#!/bin/sh
# this script builds a swapfile
# takes 3 arguments
# ./buildswap /swapfile 1024 MiB
#

FILEPATH=$1
SIZE=$2
UNIT=$3

if [ "$#" -lt 3 ] ; then
   echo $0 ERROR broken arguments, bailing
   exit 1
fi

# fallocate -l 1G /swapfile could work, but not on xfs
dd if=/dev/zero of=${FILEPATH} bs=1${UNIT} count=${SIZE}
chmod -v 600 ${FILEPATH}
mkswap ${FILEPATH}
swapon ${FILEPATH}

grep ${FILEPATH} /etc/fstab || echo "${FILEPATH} none swap  sw  0 0" >> /etc/fstab
