#!/bin/sh

if [ -r /etc/yum.repos.d/rhel-libreswan.repo ] ; then
    echo $0 repo already installed, exiting
    exit 0
fi

yum-config-manager --add-repo https://download.libreswan.org/rhel-libreswan.repo
rpm --import https://download.libreswan.org/RPM-GPG-KEY-libreswan

echo $0 repo installed
